org:
  kin:
    mqtt:
      broker:
        gossip:
          port: 5003
          alias: 'MQTTBroker1885'
          seeds: 'localhost:5001;localhost:5003'
          namespace: mqtt-broker
        port: 1885
        auth:
          users:
            JavaSubscriber:
              username: java
              password: 12345
            JavaPublisher:
              username: java
              password: 12345
server:
  port: 8003