org:
  kin:
    mqtt:
      broker:
        gossip:
          port: 5003
          alias: 'MQTTBroker1885'
          seeds: 'localhost:5001;localhost:5003'
          namespace: mqtt-broker
        port: 1885
        auth:
          users:
            java: '12345'
server:
  port: 8003

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false