org:
  kin:
    mqtt:
      broker:
        gossip:
          port: 5002
          alias: 'MQTTBroker1884'
          seeds: 'localhost:5001;localhost:5003'
          namespace: mqtt-broker
        port: 1884
        auth:
          users:
            root:
              username: java
              password: 12345
server:
  port: 8002

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false