org:
  kin:
    mqtt:
      broker:
        port: 1884
        auth:
          users:
            java: '12345'
        broker-id: B2
        cluster:
          host: localhost
          seeds: 'localhost:5001:15001,localhost:5002:15002,localhost:5003:15003'
          port: 5002
          storePort: 15002
        data-path: datas/b2
        rules:
          - name: http_route
            desc: "message from 'MQTT Examples' route to http"
            sql: "select * from 'MQTT Examples'"
            actions:
              - type: http
                args:
                  - bridgeName: local_http_route
                  - uri: "localhost:10000/mqtt/receive"
server:
  port: 8002

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

spring:
  netty:
    leak-detection: paranoid

logging:
  level:
    com:
      alipay: WARN
    io:
      scalecube: WARN