org:
  kin:
    mqtt:
      broker:
        port: 1886
        auth:
          users:
            java: '12345'
        broker-id: B4
        cluster:
          host: localhost
          seeds: 'localhost:5001:15001,localhost:5002:15002,localhost:5003:15003'
          port: 5004
          storePort: 15004
        data-path: datas/b4
server:
  port: 8004

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

spring:
  netty:
    leak-detection: paranoid

logging:
  level:
    com:
      alipay: WARN
    io:
      scalecube: WARN