org:
  kin:
    mqtt:
      broker:
        auth:
          users:
            java: '12345'
        dataPath: datas/standalone
        rules:
          - name: http_route
            desc: "message from `example` route to http"
            sql: "select * from `example`"
            actions:
              - type: http_bridge
                args:
                  bridgeName: local_http_route
                  uri: "localhost:10000/mqtt/receive"

server:
  port: 8000

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

spring:
  netty:
    leak-detection: paranoid