org:
  kin:
    mqtt:
      broker:
        auth:
          users:
            java: '12345'
        dataPath: datas/standalone

server:
  port: 8000

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

spring:
  netty:
    leak-detection: paranoid